# -*- coding: utf-8 -*-
actions = {
"up": _("Go up in the current buffer"),
"down": _("Go down in the current buffer"),
"left": _("Go to the previous buffer"),
"right": _("Go to the next buffer"),
"next_account": _("Focus the next session"),
"previous_account": _("Focus the previous session"),
"show_hide": _("Show or hide the GUI"),
"post_tweet": _("New tweet"),
"post_reply": _("Reply"),
"post_retweet": _("Retweet"),
"send_dm": _("Send direct message"),
"add_to_favourites": _("Like a tweet"),
"remove_from_favourites": _("Unlike a tweet"),
"follow": _("Open the user actions dialogue"),
"user_details": _("See user details"),
"view_item": _("Show tweet"),
"exit": _("Quit"),
"open_timeline": _("Open user timeline"),
"remove_buffer": _("Destroy buffer"),
"interact": _("Interact with the currently focused tweet."),
"url": _("Open URL"),
"volume_up": _("Increase volume by 5%"),
"volume_down": _("Decrease volume by 5%"),
"go_home": _("Jump to the first element of a buffer"),
"go_end": _("Jump to the last element of the current buffer"),
"go_page_up": _("Jump 20 elements up in the current buffer"),
"go_page_down": _("Jump 20 elements down in the current buffer"),
"update_profile": _("Edit profile"),
"delete": _("Delete a tweet or direct message"),
"clear_buffer": _("Empty the current buffer"),
"repeat_item": _("Repeat last item"),
"copy_to_clipboard": _("Copy to clipboard"),
"add_to_list": _("Add to list"),
"remove_from_list": _("Remove from list"),
"toggle_buffer_mute": _("Mute/unmute the active buffer"),
"toggle_session_mute": _("Mute/unmute the current session"),
"toggle_autoread": _("toggle the automatic reading of incoming tweets in the active buffer"),
"search": _("Search on twitter"),
"find": _("Find a string in the currently focused buffer"),
"edit_keystrokes": _("Show the keystroke editor"),
"view_user_lists": _("Show lists for a specified user"),
"get_more_items": _("load previous items"),
"reverse_geocode": _("Get geolocation"),
"view_reverse_geocode": _("Display the tweet's geolocation in a dialog"),
"get_trending_topics": _("Create a trending topics buffer"),
"open_conversation": _("View conversation"),
"check_for_updates": _("Check and download updates"),
"lists_manager": _("Opens the list manager, which allows you to create, edit, delete and open lists in buffers."),
"configuration": _("Opens the global settings dialogue"),
"accountConfiguration": _("Opens the account settings dialogue"),
"audio": _("Try to play an audio file"),
"update_buffer": _("Updates the buffer and retrieves possible lost items there."),
"ocr_image": _("Extracts the text from a picture and displays the result in a dialog."),
}