# -*- coding: utf-8 -*-
import wx

class authorisationDialog(wx.Dialog):
    def __init__(self):
        super(authorisationDialog, self).__init__(parent=None, title=_(u"Authorising account..."))
        panel = wx.Panel(self)
        sizer = wx.BoxSizer(wx.VERTICAL)
        static1 = wx.StaticText(panel, wx.NewId(), _("URL of mastodon instance:"))
        self.instance = wx.TextCtrl(panel, -1)
        sizer1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer1.Add(static1, 0, wx.ALL, 5)
        sizer1.Add(self.instance, 0, wx.ALL, 5)
        sizer.Add(sizer1, 0, wx.ALL, 5)
        static2 = wx.StaticText(panel, wx.NewId(), _("Email address:"))
        self.email = wx.TextCtrl(panel, -1)
        sizer2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer2.Add(static2, 0, wx.ALL, 5)
        sizer2.Add(self.email, 0, wx.ALL, 5)
        sizer.Add(sizer2, 0, wx.ALL, 5)
        static3 = wx.StaticText(panel, wx.NewId(), _("Password:"))
        self.password = wx.TextCtrl(panel, -1)
        sizer3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer3.Add(static3, 0, wx.ALL, 5)
        sizer3.Add(self.password, 0, wx.ALL, 5)
        sizer.Add(sizer3, 0, wx.ALL, 5)
        self.ok = wx.Button(panel, wx.ID_OK)
        self.cancel = wx.Button(panel, wx.ID_CANCEL)
        sizer4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer4.Add(self.ok, 0, wx.ALL, 5)
        sizer4.Add(self.cancel, 0, wx.ALL, 5)
        sizer.Add(sizer4, 0, wx.ALL, 5)
        panel.SetSizer(sizer)
        min = sizer.CalcMin()
        self.SetClientSize(min)
