# -*- coding: utf-8 -*-
actions = [  ("audio", _(u"The tweet may contain a playable audio")),
  ("create_timeline", _(u"A timeline has been created")),
    ("delete_timeline", _(u"A timeline has been deleted")),
    ("dm_received", _(u"You've received a direct message")),
    ("dm_sent", _(u"You've sent a direct message")),
    ("error", _(u"A bug has happened")),
  ("favourite", _(u"You've added a tweet to your favourites")),
  ("favourites_timeline_updated", _(u"Someone's favourites have been updated")),
  ("limit", _(u"There are no more tweets to read")),
    ("list_tweet", _(u"A list has a new tweet")),
    ("max_length", _(u"You can't add any more characters on the tweet")),
    ("mention_received", _(u"You've been mentioned ")),
  ("new_event", _(u"A new event has happened")),
  ("ready", _(u"TW Blue is ready ")),
    ("reply_send", _(u"You've replied")),
    ("retweet_send", _(u"You've retweeted")),
    ("search_updated", _(u"A search has been updated")),
    ("tweet_received", _(u"There's a new tweet in the main buffer")),
    ("tweet_send", _(u"You've sent a tweet")),
  ("tweet_timeline", _(u"There's a new tweet in a timeline")),
    ("update_followers", _(u"You have a new follower")),
    ("volume_changed", _(u"You've turned the volume up or down"))]