# -*- coding: utf-8 -*-
actions = {
    "up": _(u"Go up in the current buffer"),
    "down": _(u"Go down in the current buffer"),
    "left": _(u"Go to the previous buffer"),
    "right": _(u"Go to the next buffer"),
    "next_account": _(u"Focus the next session"),
    "previous_account": _(u"Focus the previous session"),
    "show_hide": _(u"Show or hide the GUI"),
    "post_tweet": _("Make a new post"),
    "post_reply": _(u"Reply"),
    "post_retweet": _(u"Repost"),
    "send_dm": _(u"Send direct message"),
    "add_to_favourites": _("Add post to likes"),
    "remove_from_favourites": _(u"Remove post from likes"),
    "toggle_like": _("Add/remove post from likes"),
    "follow": _(u"Open the user actions dialogue"),
    "user_details": _(u"See user details"),
    "view_item": _(u"Show post"),
    "exit": _(u"Quit"),
    "open_timeline": _(u"Open user timeline"),
    "remove_buffer": _(u"Destroy buffer"),
    "url": _(u"Open URL"),
    "open_in_browser": _(u"View in browser"),
    "volume_up": _(u"Increase volume by 5%"),
    "volume_down": _(u"Decrease volume by 5%"),
    "go_home": _(u"Jump to the first element of a buffer"),
    "go_end": _(u"Jump to the last element of the current buffer"),
    "go_page_up": _(u"Jump 20 elements up in the current buffer"),
    "go_page_down": _(u"Jump 20 elements down in the current buffer"),
    "delete": _("Delete post"),
    "clear_buffer": _(u"Empty the current buffer"),
    "repeat_item": _(u"Repeat last item"),
    "copy_to_clipboard": _(u"Copy to clipboard"),
    "toggle_buffer_mute": _(u"Mute/unmute the active buffer"),
    "toggle_session_mute": _(u"Mute/unmute the current session"),
    "toggle_autoread": _(u"Toggle the automatic reading of incoming posts in the active buffer"),
    "search": _(u"Search"),
    "find": _(u"Find a string in the currently focused buffer"),
    "edit_keystrokes": _(u"Show the keystroke editor"),
    "get_more_items": _(u"Load previous items"),
    "open_conversation": _(u"View conversation"),
    "check_for_updates": _(u"Check and download updates"),
    "configuration": _(u"Opens the global settings dialogue"),
    "accountConfiguration": _(u"Opens the account settings dialogue"),
    "audio": _(u"Try to play a media file"),
    "update_buffer": _(u"Updates the buffer and retrieves possible lost items there."),
    "ocr_image": _(u"Extracts the text from a picture and displays the result in a dialog."),
    "seekLeft": _(u"Seek media backward"),
    "seekRight": _(u"Seek media forward"),
    "manage_accounts": _(u"Manage accounts"),
}
