# -*- coding: utf-8 -*-
actions = {
    "up": _(u"Go up in the current buffer"),
    "down": _(u"Go down in the current buffer"),
    "left": _(u"Go to the previous buffer"),
    "right": _(u"Go to the next buffer"),
    "next_account": _(u"Focus the next session"),
    "previous_account": _(u"Focus the previous session"),
    "show_hide": _(u"Show or hide the GUI"),
    "post_tweet": _("Make a new post"),
    "post_reply": _(u"Reply"),
    "post_retweet": _(u"Boost"),
    "send_dm": _(u"Send direct message"),
    "add_to_favourites": _("Add post to favorites"),
    "remove_from_favourites": _(u"Remove post from favorites"),
    "toggle_like": _("Add/remove post from favorites"),
    "follow": _(u"Open the user actions dialogue"),
#    "user_details": _(u"See user details"),
    "view_item": _(u"Show post"),
    "exit": _(u"Quit"),
    "open_timeline": _(u"Open user timeline"),
    "remove_buffer": _(u"Destroy buffer"),
    "interact": _(u"Interact with the currently focused post."),
    "url": _(u"Open URL"),
    "open_in_browser": _(u"View in browser"),
    "volume_up": _(u"Increase volume by 5%"),
    "volume_down": _(u"Decrease volume by 5%"),
    "go_home": _(u"Jump to the first element of a buffer"),
    "go_end": _(u"Jump to the last element of the current buffer"),
    "go_page_up": _(u"Jump 20 elements up in the current buffer"),
    "go_page_down": _(u"Jump 20 elements down in the current buffer"),
#    "update_profile": _(u"Edit profile"),
    "delete": _("Delete post"),
    "clear_buffer": _(u"Empty the current buffer"),
    "repeat_item": _(u"Repeat last item"),
    "copy_to_clipboard": _(u"Copy to clipboard"),
#    "add_to_list": _(u"Add to list"),
#    "remove_from_list": _(u"Remove from list"),
    "toggle_buffer_mute": _(u"Mute/unmute the active buffer"),
    "toggle_session_mute": _(u"Mute/unmute the current session"),
    "toggle_autoread": _(u"toggle the automatic reading of incoming tweets in the active buffer"),
    "search": _(u"Search on instance"),
    "find": _(u"Find a string in the currently focused buffer"),
    "edit_keystrokes": _(u"Show the keystroke editor"),
#    "view_user_lists": _(u"Show lists for a specified user"),
    "get_more_items": _(u"load previous items"),
#    "get_trending_topics": _(u"Create a trending topics buffer"),
    "open_conversation": _(u"View conversation"),
    "check_for_updates": _(u"Check and download updates"),
    "configuration": _(u"Opens the global settings dialogue"),
#    "list_manager": _(u"Opens the list manager"),
    "accountConfiguration": _(u"Opens the account settings dialogue"),
    "audio": _(u"Try to play a media file"),
    "update_buffer": _(u"Updates the buffer and retrieves possible lost items there."),
    "ocr_image": _(u"Extracts the text from a picture and displays the result in a dialog."),
#    "add_alias": _("Adds an alias to an user"),
}